### ISSUE TITLE
Documentation: mention custom meshes should be in XZ plane.

### ISSUE THREAD

**Issue by rob-myers** [donmccurdy/three-pathfinding#67]
Thanks for the great library.

The `isVectorInPolygon` test allows deviation `lowestY - 0.5 < vector.y < highestY + 0.5`.
Implicitly, 2d points should be encoded `(x, 0, y)` when constructing a floor.

Would you mind noting this in the README?

**Comment by donmccurdy** [comment]
Good suggestion, thanks — added in https://github.com/donmccurdy/three-pathfinding/commit/b2b1db6fb74dc3277b98c760198c8b3361e57c00.

**Comment by craftoid** [comment]
Could you extend the docs to include the distance to the mesh?
I found the +/- 0.5 to be somewhat of a magic number that should be documented as well.

We were using  A-Frame with your fantastic A-Frame Extras + Recast Inspector-Plugin to quickly creating navmeshes.
Sometimes our students were confused why their player did not snap to the navmesh. It took me a while to figure out that it's probably related to the agent not spawning close enough to the navmesh...

**Comment by donmccurdy** [comment]
The idea is that the origin of the object you're moving should be as close as possible to the navmesh surface, within some floating point error. You can also use a dummy object for pathfinding and put the actual model at some offset from it. I used 0.5m here to be a little more flexible, but I wouldn't want to document that because then we'd be stuck with it. How about something like:

> The origin of an agent should initially be placed on the surface of the nav mesh. If needed, a dummy object can be used for pathfinding logic, and the rendered model for that agent may be placed at on offset as needed.

**Comment by craftoid** [comment]
Sounds good to me!

**Comment by donmccurdy** [comment]
Added in https://github.com/donmccurdy/three-pathfinding/commit/b8e44650172c5612fbadd2bbfc59ccc507c9b767 :)
